### ISSUE TITLE
Clear filename when there is no match/file

### ISSUE THREAD

**Issue by nacalai** [exeldro/obs-dir-watch-media#6]
Hi there! I am not sure if you are actively developing still, but I was hoping you could add a small feature to this plugin. We are actively using it in our TV production to easily playback videos, and would love to have this little feature implemented.

Currently, we are using a streamdeck that is outputting the different filenames that this plugin retrieves. The problem is that when we remove videos, the plugin still just uses the last filepath. It should instead just clear the path/make it empty when there is no media match found.

Could this be done? :)

**Comment by exeldro** [comment]
That is certainly possible, added it to my to-do list

**Comment by nacalai** [comment]
Thank you! Awesome. Please keep me posted

fre. 4. mar. 2022, 14:29 skrev Exeldro ***@***.***>:

**Comment by nacalai** [comment]
Hi there. Just wondering if you've had a chance to look at it? :)

**Comment by exeldro** [comment]
Can you test if this works for you?
https://github.com/exeldro/obs-dir-watch-media/actions/runs/1976857233

**Comment by nacalai** [comment]
Thanks. I haven't done extensive testing but so far it's working pretty good! It defaults to "None", which is better than it keeping the last known filename.

**Comment by nacalai** [comment]
Update: If I delete/rename media and add a new match, OBS websocket doesn't seem to output the filename before the scene is in program/switched to. From what I remember it will auto-update pretty much instantly at our show. However your plugin does find the vid and has its path entered in the source setting. So, dunno if it's your plugin causing this or not?

**Comment by nacalai** [comment]
We ran it in our production today. Works perfectly. I'll just close it. Thanks a lot!
